### ISSUE TITLE
Attestation files traffic

### ISSUE THREAD

**Issue by maciejkowalczyk** [privacysandbox/attestation#10]
We would like to estimate the expected traffic volume for the attestation files (e.g. https://example.com/.well-known/privacy-sandbox-attestations).
Are they going to be fetched by browser? When?
Will cache control headers be honoured?

**Comment by dmdabbs** [comment]
Hi @maciejkowalczyk. 

I wondered the same. When I received my dev attestations json I replied to ask,

>The json is not large, but is not minified (whitespace). Should we minimise it? Or will some sandbox bot check it daily and an optimised Chrome mechanism will distribute attestations out to billions of instances? 

The Attestation team's response was:
>You may minify if desired. We do not have a preference either way; it will not have an effect on any end users.

From that I infer that browser instances will not fetch the resource.

**Comment by shivanigithub** [comment]
> From that I infer that browser instances will not fetch the resource.

That's right, the browser instances will not fetch the resource directly. Instead a backend job will verify the file and then the file will be distributed to Chrome browsers via [component updater](https://source.chromium.org/chromium/chromium/src/+/main:components/component_updater/README.md).

**Comment by maciejkowalczyk** [comment]
Thanks for the confirmation!
