### ISSUE TITLE
Clarify location of the attestation file

### ISSUE THREAD

**Issue by alois-bissuel** [privacysandbox/attestation#11]
Hello,

In the [documentation](https://github.com/privacysandbox/attestation/blob/main/how-to-enroll.md) on how to enroll, the location of the attestation file is not really clear with regards to the origin and possible subdomains used by an adtech. 

Let's assume an adtech uses https://A.adtech.com for one Privacy Sandbox API (eg ARA) and https://B.adtech.com for another (eg Protected Audience).
In this example, should the attestation file be hosted on the common site (ie https://adtech.com/.well-known/privacy-sandbox-attestations.json) or on both origins (ie  https://A.adtech.com/.well-known/... and https://B.adtech.com/.well-known/...)?

The [documentation](https://github.com/privacysandbox/attestation/blob/main/how-to-enroll.md) speaks of site, so I assume the first answer is the correct one, but I would rather ask before making any suppositions.

Thanks a lot!

**Comment by dantsai** [comment]
This should be hosted at the site (adtech.com/.well-known-privacy-sandbox-attestations.json). Thanks!
