### ISSUE TITLE
Documentation for ServiceNotUsedForReidentification

### ISSUE THREAD

**Issue by ncheng94** [privacysandbox/attestation#14]
In https://github.com/privacysandbox/attestation, I see an explanation for ServiceNotUsedForIdentifyingUserAcrossSites. However, in the attestation file, it contains ServiceNotUsedForReidentification. I do not see documentation/explanation for ServiceNotUsedForReidentification in https://github.com/privacysandbox/attestation. Could someone clarify and add an explanation for that?

**Comment by dmdabbs** [comment]
Google has a [PR](https://github.com/privacysandbox/attestation/pull/8) for this since 20 June.
