### ISSUE TITLE
Register the .well-known file

### ISSUE THREAD

**Issue by jyasskin** [privacysandbox/attestation#17]
Using the process at https://github.com/protocol-registries/well-known-uris.

**Comment by rowan-m** [comment]
FYI @GeorgiaFranklin @lakshmy88 re: https://github.com/protocol-registries/well-known-uris/issues/54

**Comment by rowan-m** [comment]
Added to registry: https://www.iana.org/assignments/well-known-uris/well-known-uris.xhtml#:~:text=privacy%2Dsandbox%2Dattestations.json
