### ISSUE TITLE
CHIPS and Attestation?

### ISSUE THREAD

**Issue by thegreatfatzby** [privacysandbox/attestation#30]
I'm a little unclear, I don't see CHIPS called out in any of the fields for the [attestation](https://github.com/privacysandbox/attestation#validation-and-transparency-framework), should that be included?

**Comment by dmdabbs** [comment]
I assume that CHIPS does not require attestations because it is inherently not a cross site mechanism.

**Comment by rowan-m** [comment]
Correct, CHIPs (adding the `Partitioned` attribute to a cookie) does not require attestation.
