### ISSUE TITLE
Enrollment fields clarification

### ISSUE THREAD

**Issue by dmdabbs** [privacysandbox/attestation#5]
Must the point of contact be an individual's name, or can the name be a group, say 'Sandbox Platform Team' or similar?

The form requests two e-mail addresses, a _point of contact_ and _organisational support_. 
Confirming that the former is solely for outreach from Google, such as technical/business questions and will not be published, and that the latter is for inquries from the public and will be published. 

The point-of-contact email address must be a "corporate email address that matches your organization's domain." By _organization's domain_ you refer to the entity's corporate web presence, not the domain it will use for activating the APIs?

Where do you intend to publish the public-facing address?

**Comment by GeorgiaFranklin** [comment]
It's preferable to have an individual's name as the 'Point of Contact' so Google has someone directly to reach out to with any questions about the enrollment submission, but the 'Point of Contact' email can be a group (distribution list). The Point of Contact name/email would not be published anywhere publicly. And yes, the organizational support email is for inquiries from the public and would be published. 

The point of contact email should align with the entity's corporate web presence.

The public facing email address will be published on future reports that are provided to the general public (ie. somewhere accessible for all).

**Comment by dmdabbs** [comment]
Thanks for confirmation, Georgia.
