### ISSUE TITLE
It is not possible to request a D-U-N-S number through the enrollment form

### ISSUE THREAD

**Issue by v1x4l** [privacysandbox/attestation#52]
I tried to request a D-U-N-S as the first step in the [enrollment process](https://docs.google.com/forms/d/e/1FAIpQLSehzvBN65Tce--ryGhyHuY0fqfAId2Q6fMbUh4KHZhheFjqMw/viewform). However it requires me to fill out a point of contact which I can't because it requires me to insert a number:

![image](https://github.com/privacysandbox/attestation/assets/15781670/c4fc4fd0-6840-4334-9587-e19463577d03)

How do I proceed?

**Comment by dantsai** [comment]
Apologies for that; can you please try again now?

**Comment by v1x4l** [comment]
No problem - now it works. Thanks :)

**Comment by osnek642** [comment]
`
